language: java
git:
  quiet: true
branches:
  only:
    - master
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ant dist
before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  script:
    - gem install faraday -v 0.15.4
  provider: releases
  api_key:
    secure: hvOTbR8Yyw+fC23Atfp69VqnLQMg1NXADC3oUmmZxdjjeUq7oZSRm/NlFxb1Thu/qrQj3c7yWRW3+5AYvaaI4WRIiFAtpyhQdfF69IBtJATh36cXIwzTYKfv2kWCYr+ZsKXVnl7rO6iu4EzeyQ8CSQdQ22qqAe2bYynEMDstknCpxM8k5oF/5lsSweL8qMqNbxWzfcwwBEJNDpx0UQXakSRfdIDWNOw9S2JGkHQDWdyFFcMni2x4aQWqKpLIL/FpIVmcqPoettEqPM+UoZ5YHnOWvOWD/c7dxcWqQ1xJTnq7wtu81qOFHTRIY5AYQH58GxmB4nSfQijFqyem88REgIbJHo65O7pe36yGT/YbsDybX0PRXGOTUFOag90Fos4NN9aC96hfV0rrrahxXpBGloo+qnUL2tx9wQBRBjSB4FgpletUPyYAArvBMJ1MeUebt9gdC/GMdn7RMEQ/SBse3zXpp02NtxmBynPP3Z6qd2iLyNNmLqxcyOntzQkV/XReJAfU5YXdDDinM8PiyjTNiWVKts0YlYHYJObz2QUBJ+nZch1Jb1m1iS66qiugvJvt62C9SaeX34ITBtemtroanFqTkvFMbAsCC5IwAjJslCvmPUdXuqL2e4TI7s6TSy7girgTfqivpQQf/I4fTGD3gpgw8OArAGBB/7YE/A4OdfQ=
  file: MedTagger.zip
  skip_cleanup: true
