language: java
git:
  quiet: true
env:
  global:
    - secure: jvgtG0aiIZQDMvzkJZfejtbvVfY/1Wgr9HGe+WBuklXtrkCJ2Eu21yWE4wJFRWcNg+h6W754fEArn7bi751YIVgz/6Agufb6RGdGeM17PjKffchxVFDQcGJHDIBwB6VeUu0s5rtJ6CrSMwBMw2Nl9AYuxiu8mFj55NqsD0MwFPcDogPWYkJmVnhbyeudNiT48jHeNv64EA/qBax8x/j18HNZa5id9HQnJ6oEAJevsuEKyGSgiZNTxagnEy8m2KakP+5mBm2InwdJKmEsZP3ipfpdOn5C3Y4By8UERalBBhrvtea0EDGZrVZdl5J3z0iPPDDqTcHRG6za5JysurwOpJMbm4rqfhIJAeJKYPB52vEBvebtLjqyk40e0EhCDPQvTIp1Ko/JdLAjF59NPp4g+34ACHxdjnsnuHSCDJ4FpUn9IHpwB7DfBM6k6FhQ4LiOpINRE0tMydXkawr49acFDyJeyORbRybOtNVzlyRpFY+ktFBxNLrZ/G5+z8FVQLuJqckDsQe5pXhMfKldSl6JWW1QZ7IqDtmn0dD0mU7xjsKCgJq/NNpc+Bc4W1y5wIuMrIEZx3+/RO0EEszf1XxsZtwW8/1drGTtN5iPsSjm4cbX3QwTH/9kjLolPP9pqtTlti/APbkVrkCni/wIhsV6hxBzBK5RP8Wts1pMWkpP0iU=
branches:
  only:
    - master
    - /v\d+\.\d+[a-zA-Z-_]+?(\.\d+[a-zA-Z-_]+?)/
install:
  - mvn clean deploy -Pbuild-deploy -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dtoken=$DEPLOY_KEY
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ant dist
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: dE3wu/mj4290JbKl/9XV3HYVjufALDxQNjAfi0MWOq0ZAzZ+v2/bXj9q7w1dc3jNf50FLk4EWkG7yoW213tYVqcMrUHfr1p3Pm7qpGtDfNMAR9ZisUN3cx1HGXGCXQjA8tANV3rNeMw7YyS52WLZPg724T8HX4pDyyV2Swxw//gYzXNXelGjSMjt2v/1B3QnK66VnAiTzz/zXGv5rJgdu+7BOSLFOq05IpXf/MMUxh0rZ/VTJvV3UxrrcSs1uT0hUi6dAthQPg6uxisQuy+ZIXDJKuRZgbOTqdzrZlCq/V2lA+FNixyowAlko8cVh6V1f6uoG2P7L4QDQN3r/KBdql5pp1X+MB6tqiKkyUwOO6dzGk968Vsn2cU9VRpmqccai2gKUXTgfrvK7GS1JmxKsfWxSRKv/WXkGeD71ixKViRv0fIsgr4gBKHTPRHsbe3QMPW+R4fa2GlCdU0pG/BcFpFe/OTomeiQL+f5h+kwN7F4Nt52hi2+OddCDoVyC++sppEFq8GYgrJBpuFIe+XsqXacNs708qbK4wV7sFGctjQ4LDDh5xpIoiUvNLVt7amdlOaNk/++iM8Pj/pANCb0882LzkoasRFJNtrhdPDRkwKt82oEPJ6J9MQn9WUN3W8tgJ8KPn2/oQP7JkWORKH1C9zlXF6w1tA0uPIijWaAF80=
  file: MedTagger.zip
  on:
    tags: true
  skip_cleanup: true
